python six_rolling.py --fpweight 0.5
python six_rolling.py --fpweight 1.0
python six_rolling.py --fpweight 1.5
python six_rolling.py --fpweight 2.0
python six_rolling.py --fpweight 3.0
python six_rolling.py --fpweight 4.5
python six_rolling.py --fpweight 6.0
python six_rolling.py --fpweight 10
python six_rolling.py --fpweight 20
