scimaf_dir --long_micro --db baseline_v2.0_10yrs.db
scimaf_dir --long_micro --db carina_v2.0_10yrs.db
scimaf_dir --long_micro --db ddf_frac_ddf_per0.6_v2.0_10yrs.db
scimaf_dir --long_micro --db local_gal_bindx2_v2.0_10yrs.db
scimaf_dir --long_micro --db long_gaps_nightsoff0_delayed-1_v2.0_10yrs.db
scimaf_dir --long_micro --db long_gaps_nightsoff1_delayed1827_v2.0_10yrs.db
scimaf_dir --long_micro --db long_gaps_nightsoff3_delayed-1_v2.0_10yrs.db
scimaf_dir --long_micro --db long_gaps_nightsoff5_delayed-1_v2.0_10yrs.db
scimaf_dir --long_micro --db long_gaps_nightsoff5_delayed1827_v2.0_10yrs.db
scimaf_dir --long_micro --db long_gaps_nightsoff6_delayed1827_v2.0_10yrs.db
scimaf_dir --long_micro --db long_gaps_nightsoff7_delayed-1_v2.0_10yrs.db
scimaf_dir --long_micro --db long_gaps_np_nightsoff0_delayed-1_v2.0_10yrs.db
scimaf_dir --long_micro --db long_gaps_np_nightsoff0_delayed1827_v2.0_10yrs.db
scimaf_dir --long_micro --db long_gaps_np_nightsoff1_delayed-1_v2.0_10yrs.db
scimaf_dir --long_micro --db long_gaps_np_nightsoff1_delayed1827_v2.0_10yrs.db
scimaf_dir --long_micro --db long_gaps_np_nightsoff2_delayed-1_v2.0_10yrs.db
scimaf_dir --long_micro --db long_gaps_np_nightsoff3_delayed-1_v2.0_10yrs.db
scimaf_dir --long_micro --db long_gaps_np_nightsoff4_delayed-1_v2.0_10yrs.db
scimaf_dir --long_micro --db long_gaps_np_nightsoff4_delayed1827_v2.0_10yrs.db
scimaf_dir --long_micro --db long_gaps_np_nightsoff5_delayed-1_v2.0_10yrs.db
scimaf_dir --long_micro --db long_gaps_np_nightsoff6_delayed1827_v2.0_10yrs.db
scimaf_dir --long_micro --db long_gaps_np_nightsoff7_delayed1827_v2.0_10yrs.db
scimaf_dir --long_micro --db long_u1_v2.0_10yrs.db
scimaf_dir --long_micro --db multi_short_v2.0_10yrs.db
scimaf_dir --long_micro --db north_stripe_v2.0_10yrs.db
scimaf_dir --long_micro --db presto_gap1.5_v2.0_10yrs.db
scimaf_dir --long_micro --db presto_gap2.0_mix_v2.0_10yrs.db
scimaf_dir --long_micro --db presto_gap2.0_v2.0_10yrs.db
scimaf_dir --long_micro --db presto_gap2.5_mix_v2.0_10yrs.db
scimaf_dir --long_micro --db presto_gap3.5_mix_v2.0_10yrs.db
scimaf_dir --long_micro --db presto_gap3.5_v2.0_10yrs.db
scimaf_dir --long_micro --db presto_gap4.0_v2.0_10yrs.db
scimaf_dir --long_micro --db presto_half_gap1.5_mix_v2.0_10yrs.db
scimaf_dir --long_micro --db presto_half_gap1.5_v2.0_10yrs.db
scimaf_dir --long_micro --db presto_half_gap2.0_mix_v2.0_10yrs.db
scimaf_dir --long_micro --db presto_half_gap2.0_v2.0_10yrs.db
scimaf_dir --long_micro --db presto_half_gap2.5_mix_v2.0_10yrs.db
scimaf_dir --long_micro --db presto_half_gap2.5_v2.0_10yrs.db
scimaf_dir --long_micro --db presto_half_gap3.0_v2.0_10yrs.db
scimaf_dir --long_micro --db presto_half_gap3.5_mix_v2.0_10yrs.db
scimaf_dir --long_micro --db roll_early_v2.0_10yrs.db
scimaf_dir --long_micro --db rolling_all_sky_ns2_rw0.9_v2.0_10yrs.db
scimaf_dir --long_micro --db rolling_bulge_ns2_rw0.5_v2.0_10yrs.db
scimaf_dir --long_micro --db rolling_ns2_rw0.5_v2.0_10yrs.db
scimaf_dir --long_micro --db rolling_ns2_rw0.9_v2.0_10yrs.db
scimaf_dir --long_micro --db rolling_ns3_rw0.9_v2.0_10yrs.db
scimaf_dir --long_micro --db short_exp_v2.0_10yrs.db
scimaf_dir --long_micro --db six_rolling_ns6_rw0.5_v2.0_10yrs.db
scimaf_dir --long_micro --db twilight_neo_nightpattern4v2.0_10yrs.db
scimaf_dir --long_micro --db twilight_neo_nightpattern5v2.0_10yrs.db
scimaf_dir --long_micro --db twilight_neo_nightpattern7v2.0_10yrs.db
scimaf_dir --long_micro --db vary_gp_gpfrac0.01_v2.0_10yrs.db
scimaf_dir --long_micro --db vary_gp_gpfrac0.10_v2.0_10yrs.db
scimaf_dir --long_micro --db vary_gp_gpfrac0.15_v2.0_10yrs.db
scimaf_dir --long_micro --db vary_gp_gpfrac0.20_v2.0_10yrs.db
scimaf_dir --long_micro --db vary_gp_gpfrac0.40_v2.0_10yrs.db
scimaf_dir --long_micro --db vary_gp_gpfrac0.45_v2.0_10yrs.db
scimaf_dir --long_micro --db vary_gp_gpfrac0.50_v2.0_10yrs.db
scimaf_dir --long_micro --db vary_gp_gpfrac0.75_v2.0_10yrs.db
scimaf_dir --long_micro --db vary_gp_gpfrac1.00_v2.0_10yrs.db
