scimaf_dir --db long_gaps_nightsoff0_v2.0_10yrs.db
scimaf_dir --db long_gaps_nightsoff1_v2.0_10yrs.db
scimaf_dir --db long_gaps_nightsoff2_v2.0_10yrs.db
scimaf_dir --db long_gaps_nightsoff3_v2.0_10yrs.db
scimaf_dir --db long_gaps_nightsoff4_v2.0_10yrs.db
scimaf_dir --db long_gaps_nightsoff5_v2.0_10yrs.db
scimaf_dir --db long_gaps_nightsoff6_v2.0_10yrs.db
scimaf_dir --db long_gaps_nightsoff7_v2.0_10yrs.db
glance_dir --db long_gaps_nightsoff0_v2.0_10yrs.db
glance_dir --db long_gaps_nightsoff1_v2.0_10yrs.db
glance_dir --db long_gaps_nightsoff2_v2.0_10yrs.db
glance_dir --db long_gaps_nightsoff3_v2.0_10yrs.db
glance_dir --db long_gaps_nightsoff4_v2.0_10yrs.db
glance_dir --db long_gaps_nightsoff5_v2.0_10yrs.db
glance_dir --db long_gaps_nightsoff6_v2.0_10yrs.db
glance_dir --db long_gaps_nightsoff7_v2.0_10yrs.db
