python weight_scan.py --fp_weight 0.1
python weight_scan.py --fp_weight 0.3
python weight_scan.py --fp_weight 0.6
python weight_scan.py --fp_weight 1.0
python weight_scan.py --fp_weight 1.5
python weight_scan.py --fp_weight 3
python weight_scan.py --fp_weight 6
python weight_scan.py --fp_weight 10
python weight_scan.py --fp_weight 20
