scimaf_dir --db twilight_neo_nightpattern1v2.0_10yrs.db
scimaf_dir --db twilight_neo_nightpattern2v2.0_10yrs.db
scimaf_dir --db twilight_neo_nightpattern3v2.0_10yrs.db
scimaf_dir --db twilight_neo_nightpattern4v2.0_10yrs.db
scimaf_dir --db twilight_neo_nightpattern5v2.0_10yrs.db
scimaf_dir --db twilight_neo_nightpattern6v2.0_10yrs.db
scimaf_dir --db twilight_neo_nightpattern7v2.0_10yrs.db
glance_dir --db twilight_neo_nightpattern1v2.0_10yrs.db
glance_dir --db twilight_neo_nightpattern2v2.0_10yrs.db
glance_dir --db twilight_neo_nightpattern3v2.0_10yrs.db
glance_dir --db twilight_neo_nightpattern4v2.0_10yrs.db
glance_dir --db twilight_neo_nightpattern5v2.0_10yrs.db
glance_dir --db twilight_neo_nightpattern6v2.0_10yrs.db
glance_dir --db twilight_neo_nightpattern7v2.0_10yrs.db
